### ISSUE TITLE
inner setup.py yaml links won't work

### ISSUE THREAD

**Issue by bendichter** [nwb-extensions/ndx-template#13]
The links from the setup.py file to the yaml files are the correct relative path for the outer setup.py file but not for the inner one. Is there a way to bring the yaml files along for the inner setup.py?

**Comment by rly** [comment]
What do you mean by the inner setup.py? I think there should be only one setup.py in the root directory. The Google drive doc says there should be one in <root>/src/pynwb/, but I think that should be changed so that the one setup.py is just in <root>/

**Comment by bendichter** [comment]
ok, I agree. Let's modify https://github.com/nwb-extensions/ndx-template/blob/master/%7B%7B%20cookiecutter.namespace%20%7D%7D/NEXTSTEPS.md accordingly
