### ISSUE TITLE
step 11 confusion

### ISSUE THREAD

**Issue by bendichter** [nwb-extensions/ndx-template#19]
For src, should we include the URL of the GitHub repo page (.com) or of the repo itself (.git)?

**Comment by rly** [comment]
The `src` link should be to the repo page on GitHub/BitBucket/GitLab, e.g. 
https://github.com/bendichter/ndx-miniscope

The `pip` field should be to the project page on PyPI, e.g.
https://pypi.org/project/ndx-miniscope

Separately, there should be a tagged release for the websites specified with the version number specified. e.g.
if `version` is 0.1.0, then these pages should exist:
https://github.com/bendichter/ndx-miniscope/releases/tag/0.1.0
https://pypi.org/project/ndx-miniscope/0.1.0

I'll add these notes to the documentation.
