### ISSUE TITLE
Support list of authors and contacts

### ISSUE THREAD

**Issue by oruebel** [nwb-extensions/ndx-template#26]
Currently cookiecutter asks for a single author. When multiple authors are entered as a comma-separated list, then this will be placed in the namespace file as a single string, e.g.,:

```
author: ' Author-A, Author-B'
```

instead of a YAML list:

```
author:
  - Author-A
  - Author-B
```

The same is true of the contacts. It would be nice to be able to render these as a list in YAML as well. This is by no means critical, since this can be edited very easily, but I figured I should document this in an issue.

**Comment by rly** [comment]
Fixed by https://github.com/nwb-extensions/ndx-template/commit/84a0384bf6bf0a3a00394cbc1c70f7b6736a6123
