### ISSUE TITLE
Add setup.cfg configuration

### ISSUE THREAD

**Issue by oruebel** [nwb-extensions/ndx-template#29]
In addition to the setup.py file it would be useful to also include a setup.cfg file with the recommended configurations for flake8 etc. with the template. A simple default ``setup.cfg`` could look like this (derived from what we have in HDMF):

```
[wheel]
universal = 1

[flake8]
max-line-length = 120
max-complexity = 17
exclude =
  .git,
  .tox,
  __pycache__,
  build/,
  dist/,
  docs/source/conf.py
  versioneer.py

[metadata]
description-file = README.rst
```

If we also want to recommend the use of versioneer then we should include those settings here as well.

**Comment by rly** [comment]
I agree, it's good to have those defaults in place. I think versioneer would add another level of complexity for anyone unfamiliar with it though. I say to keep it simple and not include it. Users can add versioneer and the setup.cfg settings if they so choose.
