### ISSUE TITLE
Add tests folder and instructions for setting up CI

### ISSUE THREAD

**Issue by rly** [nwb-extensions/ndx-template#32]
As suggested by @oruebel, it would be nice to provide instructions for extension developers of how to set up CI for their extensions and custom classes, and then run the unit and integration tests.

**Comment by rly** [comment]
TODO: Create GitHub Actions workflow file to run tests. This should be relatively easy now that GitHub Actions is mature.

**Comment by bendichter** [comment]
@rly can we assign this one to someone?

**Comment by rly** [comment]
@bendichter I will see if @mavaylon has some bandwidth for this.

**Comment by bendichter** [comment]
ok. If not, @chyumin is in between projects at the moment
