### ISSUE TITLE
specify min value of pynwb/hdmf

### ISSUE THREAD

**Issue by bendichter** [nwb-extensions/ndx-template#33]
Since `export_spec` was moved, this does not work if an older version is used because the import fails.

**Comment by rly** [comment]
@bendichter are you using the latest ndx-template? The `setup.py` and `requirements.txt` specify `"pynwb>=1.1.2"`

**Comment by bendichter** [comment]
Yes but the "Getting started" section of the README instructs you to only run

```
python -m pip install cookiecutter "nwb-docutils>=0.3.1"
```
does not get you pynwb>=1.1.2

**Comment by rly** [comment]
Fixed in https://github.com/nwb-extensions/ndx-template/commit/b947f3e6725dff066d5a46c86ed8670e56e3dea8
