### ISSUE TITLE
Make repository a Github template repository

### ISSUE THREAD

**Issue by edeno** [nwb-extensions/ndx-template#43]
Github has an easy way of [making repositories templates](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository). This includes a nice button and a "generate" endpoint that you can direct users in order to make a new template repository.

**Comment by rly** [comment]
GitHub templates look nice, but they do not allow "Mad Libs"-style filling in of user information that cookiecutter allows. As far as I can tell, a GitHub template just creates a new repo that is a mirror copy of the template repo.
